name: "Deploy typedoc to Pages"

on:
    push:
        branches: ["main"]

permissions:
    pages: write
    id-token: write

jobs:
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                repository: valapi/node-valapi
            - name: Setup Pages
              uses: actions/configure-pages@v5
            - name: Setup Node
              uses: "actions/setup-node@v4"
            - name: Install Dependencies
              run: npm install
            - name: Compile
              run: npm run compile
            - name: Build
              run: npm run docs
            - name: Upload artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: './docs'
            - name: Deploy to GitHub Pages
              uses: actions/deploy-pages@v4
